/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bouncy: typeof import('./src/components/Bouncy.vue')['default']
    Cells: typeof import('./src/components/Cells.vue')['default']
    Checkbox: typeof import('./src/components/Liquid/Checkbox.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    DarkToggle: typeof import('./src/components/DarkToggle.vue')['default']
    Dyamic: typeof import('./src/components/Dyamic.vue')['default']
    Faded: typeof import('./src/components/Title/Faded.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Fuck: typeof import('./src/components/Fuck.vue')['default']
    Glow: typeof import('./src/components/buttons/Glow.vue')['default']
    Gradient: typeof import('./src/components/Title/Gradient.vue')['default']
    GradientBorder: typeof import('./src/components/buttons/GradientBorder.vue')['default']
    InputEntry: typeof import('./src/components/InputEntry.vue')['default']
    Inset: typeof import('./src/components/Title/Inset.vue')['default']
    Liquid: typeof import('./src/components/Title/Liquid.vue')['default']
    Logos: typeof import('./src/components/Logos.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NStatistic: typeof import('naive-ui')['NStatistic']
    PageView: typeof import('./src/components/PageView.vue')['default']
    Particle: typeof import('./src/components/buttons/Particle.vue')['default']
    Radio: typeof import('./src/components/Liquid/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Smoke: typeof import('./src/components/buttons/Smoke.vue')['default']
    Switch: typeof import('./src/components/Liquid/Switch.vue')['default']
    The3dSwitch: typeof import('./src/components/The3dSwitch.vue')['default']
    TheColorModeSwitch: typeof import('./src/components/TheColorModeSwitch.vue')['default']
    TheContent: typeof import('./src/components/TheContent.vue')['default']
    TheDarkCanvas: typeof import('./src/components/TheDarkCanvas.vue')['default']
    TheDarkScroller: typeof import('./src/components/TheDarkScroller.vue')['default']
    TheDebugger: typeof import('./src/components/TheDebugger.vue')['default']
    TheFloatingMenu: typeof import('./src/components/TheFloatingMenu.vue')['default']
    TheHamburger: typeof import('./src/components/TheHamburger.vue')['default']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
    TheMagicMouse: typeof import('./src/components/TheMagicMouse.vue')['default']
    TheProvider: typeof import('./src/components/TheProvider.vue')['default']
    TheSmokeBg: typeof import('./src/components/backgrounds/TheSmokeBg.vue')['default']
    TheSplash: typeof import('./src/components/TheSplash.vue')['default']
    TheSwarm: typeof import('./src/components/TheSwarm.vue')['default']
  }
}
